# Generated by Django 4.0.2 on 2022-03-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('accounts', '0005_likesblog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likesblog',
            unique_together={('blog', 'user')},
        ),
    ]
