# Generated by Django 4.0.2 on 2022-03-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('accounts', '0007_alter_comments_restaurant_alter_comments_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesblog',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogliked', to='blogs.blog'),
        ),
    ]
